name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
      
      - name: Get version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.TAG_NAME }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## What's Changed
            
            See the full changelog for details.
            
            ## Installation
            
            Install directly from this release:
            ```bash
            pipx install git+https://github.com/speakman/llmcontext.git@${{ steps.get_version.outputs.TAG_NAME }}
            ```
            
            Or clone and install locally:
            ```bash
            git clone https://github.com/speakman/llmcontext.git
            cd llmcontext
            pip install -e .
            ```